#!/usr/bin/env python3
"""sk harness init — Scaffold a universal project harness."""

import argparse
import json
import os
import sys

if os.name == "nt":
    sys.stdout.reconfigure(encoding="utf-8")

HARNESS_YAML_TEMPLATE = """\
# harness.yaml — Universal project harness config
# Generated by: sk harness init
# Docs: https://github.com/magicpro97/copilot-session-knowledge/blob/main/docs/HARNESS-PHILOSOPHY.md
version: "1.0"

project:
  name: "{name}"
  type: "{type}"
  description: ""
  root: "."

commands:
  test:  "{test_cmd}"
  lint:  "{lint_cmd}"

success_criteria:
  - id: "tests-pass"
    description: "All tests pass"
    verify_cmd: "{test_cmd}"
    required: true
  - id: "lint-clean"
    description: "No lint errors"
    verify_cmd: "{lint_cmd}"
    required: false

reporting:
  format: "jsonl"
  output_dir: ".harness/reports/"
  telemetry: true

# Uncomment to enable SK_HARNESS dispatch middleware:
# harness_middleware: true
"""

CI_YAML_TEMPLATE = """\
# .github/workflows/harness-ci.yml
# Generated by: sk harness init
name: Harness CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  harness-gates:
    name: Harness Quality Gates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: {test_cmd}
      - name: Run lint
        run: {lint_cmd}
        continue-on-error: true
"""

GITIGNORE_LINES = [
    "# Harness reports",
    ".copilot/harness-reports/",
    ".harness/reports/",
]


def _detect_node_pm(target_dir: str) -> str:
    for lockfile, pm in [
        ("bun.lockb", "bun"),
        ("bun.lock", "bun"),
        ("pnpm-lock.yaml", "pnpm"),
        ("yarn.lock", "yarn"),
    ]:
        if os.path.exists(os.path.join(target_dir, lockfile)):
            return pm
    return "npm"


def _detect_project(target_dir: str) -> dict:
    markers = [
        ("pyproject.toml", "python-uv", "python3 -m pytest", "python3 -m ruff check ."),
        ("requirements.txt", "python-pip", "python3 -m pytest", "python3 -m ruff check ."),
        ("setup.py", "python-pip", "python3 -m pytest", "python3 -m ruff check ."),
        ("Cargo.toml", "rust", "cargo test", "cargo clippy -- -D warnings"),
        ("go.mod", "go", "go test ./...", "go vet ./..."),
        ("pom.xml", "java-maven", "mvn test -q", "mvn checkstyle:check -q"),
        ("build.gradle", "java-gradle", "./gradlew test -q", "./gradlew check -q"),
    ]

    proj_type = "unknown"
    test_cmd = "echo 'no tests configured'"
    lint_cmd = "echo 'no lint configured'"

    for filename, ptype, tcmd, lcmd in markers:
        if os.path.exists(os.path.join(target_dir, filename)):
            proj_type = ptype
            test_cmd = tcmd
            lint_cmd = lcmd
            break

    if os.path.exists(os.path.join(target_dir, "package.json")):
        pm = _detect_node_pm(target_dir)
        proj_type = "node"
        test_cmd = f"{pm} test"
        lint_cmd = f"{pm} run lint"

    return {
        "type": proj_type,
        "test_cmd": test_cmd,
        "lint_cmd": lint_cmd,
        "has_git": os.path.isdir(os.path.join(target_dir, ".git")),
        "has_github": os.path.isdir(os.path.join(target_dir, ".github")),
        "has_copilot": os.path.isdir(os.path.join(target_dir, ".copilot")),
        "has_claude": (
            os.path.isdir(os.path.join(target_dir, ".claude")) or os.path.exists(os.path.join(target_dir, "CLAUDE.md"))
        ),
    }


def _write_file(path: str, content: str) -> None:
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
    except PermissionError as exc:
        print(f"✗ Permission denied writing {path}: {exc}")
        print("  Try: sudo sk harness init")
        raise


def _create_harness_dirs(target_dir: str) -> None:
    for subdir in ["", "tasks", "reports"]:
        dirpath = os.path.join(target_dir, ".harness", subdir) if subdir else os.path.join(target_dir, ".harness")
        os.makedirs(dirpath, exist_ok=True)
        gitkeep = os.path.join(dirpath, ".gitkeep")
        if not os.path.exists(gitkeep):
            open(gitkeep, "w").close()


def _update_gitignore(target_dir: str) -> None:
    gitignore_path = os.path.join(target_dir, ".gitignore")
    existing = ""
    if os.path.exists(gitignore_path):
        try:
            with open(gitignore_path, encoding="utf-8") as f:
                existing = f.read()
        except OSError:
            pass

    missing = [ln for ln in GITIGNORE_LINES if ln not in existing]
    if not missing:
        return

    try:
        with open(gitignore_path, "a", encoding="utf-8") as f:
            if existing and not existing.endswith("\n"):
                f.write("\n")
            f.write("\n".join(missing) + "\n")
    except PermissionError as exc:
        print(f"  Warning: could not update .gitignore: {exc}")


def _confirm(prompt: str, default: bool = True) -> bool:
    hint = "[Y/n]" if default else "[y/N]"
    try:
        ans = input(f"{prompt} {hint}: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        return default
    if ans == "":
        return default
    return ans in ("y", "yes")


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="sk harness init",
        description="Scaffold a universal project harness",
    )
    parser.add_argument("--target", default=None, help="Target directory (default: cwd)")
    parser.add_argument("--name", default=None, help="Project name (default: directory basename)")
    parser.add_argument("--skeleton-only", action="store_true", help="Create .harness/ dirs only")
    parser.add_argument("--ci", action="store_true", help="Create GitHub Actions CI workflow")
    parser.add_argument("--no-ci", action="store_true", help="Skip CI workflow creation")
    parser.add_argument("--yes", "-y", action="store_true", help="Non-interactive (accept defaults)")
    parser.add_argument("--force", action="store_true", help="Overwrite existing harness.yaml")
    parser.add_argument("--json", action="store_true", dest="output_json", help="Output result as JSON")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    target = os.path.abspath(args.target or os.getcwd())
    if not os.path.isdir(target):
        print(f"✗ Target directory does not exist: {target}")
        return 1

    name = args.name or os.path.basename(target)
    info = _detect_project(target)

    harness_yaml_path = os.path.join(target, "harness.yaml")
    if os.path.exists(harness_yaml_path) and not args.force and not args.skeleton_only:
        if args.output_json:
            print(json.dumps({"status": "error", "error": "harness.yaml already exists", "path": harness_yaml_path}))
        else:
            print(f"✗ harness.yaml already exists at {harness_yaml_path}")
            print("  Use --force to overwrite.")
        return 1

    if not args.yes:
        print(f"Detected project type: {info['type']}")
        print(f"  test_cmd: {info['test_cmd']}")
        print(f"  lint_cmd: {info['lint_cmd']}")
        if not _confirm(f"Initialize harness in {target}?", default=True):
            print("Aborted.")
            return 0

    created: list[str] = []

    # Skeleton directories
    try:
        _create_harness_dirs(target)
        created.append(".harness/")
    except OSError as exc:
        print(f"✗ Failed to create .harness/ dirs: {exc}")
        return 1

    if args.skeleton_only:
        if args.output_json:
            print(json.dumps({"status": "ok", "target": target, "created": [".harness/"], "project": info}))
        else:
            print("✓ .harness/ directory initialized (skeleton-only)")
        return 0

    # harness.yaml
    yaml_content = HARNESS_YAML_TEMPLATE.format(
        name=name,
        type=info["type"],
        test_cmd=info["test_cmd"],
        lint_cmd=info["lint_cmd"],
    )
    try:
        _write_file(harness_yaml_path, yaml_content)
        created.append("harness.yaml")
    except OSError as exc:
        print(f"✗ Failed to write harness.yaml: {exc}")
        return 1

    # CI workflow
    create_ci = False
    if args.ci:
        create_ci = True
    elif not args.no_ci:
        show_ci_prompt = info["has_github"] or args.ci
        if show_ci_prompt and not args.yes:
            create_ci = _confirm("Create .github/workflows/harness-ci.yml?", default=True)
        elif args.yes and info["has_github"]:
            create_ci = True

    if create_ci:
        ci_path = os.path.join(target, ".github", "workflows", "harness-ci.yml")
        ci_content = CI_YAML_TEMPLATE.format(
            test_cmd=info["test_cmd"],
            lint_cmd=info["lint_cmd"],
        )
        try:
            _write_file(ci_path, ci_content)
            created.append(".github/workflows/harness-ci.yml")
        except OSError as exc:
            print(f"  Warning: could not write CI workflow: {exc}")

    # .gitignore
    _update_gitignore(target)

    if args.output_json:
        print(json.dumps({"status": "ok", "target": target, "created": created, "project": info}))
        return 0

    print(f"✓ harness.yaml created at {harness_yaml_path}")
    print("✓ .harness/ directory initialized")
    if ".github/workflows/harness-ci.yml" in created:
        print("✓ .github/workflows/harness-ci.yml created")
    print()
    print("Next steps:")
    print("  export SK_HARNESS=1         # Enable dispatch middleware")
    print("  sk harness doctor           # Verify setup")
    print("  sk harness check            # Verify all scripts exist")
    print()
    print("Docs: docs/HARNESS-PHILOSOPHY.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
