-- Seed data for browse_graph_api_test.rs
-- Fixture: 4 knowledge_entries across 2 wings, 2 rooms, 3+ categories;
--          4 entity_relations covering entry-match, unknown-entity, and
--          duplicate unknown-subject deduplication.
-- Golden JSON generated by Python _build_graph_data with empty filters, limit=500.

PRAGMA journal_mode=WAL;

CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER NOT NULL,
    name    TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS knowledge_entries (
    id          INTEGER PRIMARY KEY,
    category    TEXT NOT NULL DEFAULT '',
    title       TEXT NOT NULL DEFAULT '',
    content     TEXT NOT NULL DEFAULT '',
    tags        TEXT NOT NULL DEFAULT '',
    wing        TEXT,
    room        TEXT,
    confidence  REAL NOT NULL DEFAULT 0.5,
    deleted_at  INTEGER
);

-- entity_relations uses subject/predicate/object (title-based graph)
CREATE TABLE IF NOT EXISTS entity_relations (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    subject   TEXT NOT NULL,
    predicate TEXT NOT NULL,
    object    TEXT NOT NULL
);

INSERT INTO schema_version (version, name) VALUES (1, 'test');

-- 4 entries: 2 wings (backend, frontend), 2 rooms (auth, ui), 4 categories
INSERT INTO knowledge_entries (id, category, title, content, tags, wing, room)
VALUES
    (10, 'pattern',   'Auth Pattern',   '', '', 'backend',  'auth'),
    (9,  'mistake',   'Login Bug',      '', '', 'backend',  'auth'),
    (8,  'decision',  'UI Decision',    '', '', 'frontend', 'ui'),
    (7,  'discovery', 'CSS Discovery',  '', '', 'frontend', 'ui');

-- 4 entity relations:
-- 1. Entry-to-entry: Auth Pattern -> Login Bug (both match known titles)
-- 2. Entry-to-unknown: Auth Pattern -> External Auth Service (entity node created)
-- 3. Unknown-to-entry: External Auth Service -> Login Bug (dedupe: same entity, no new node)
-- 4. Unknown-to-entry: Unknown Tool -> UI Decision (new entity node)
INSERT INTO entity_relations (subject, predicate, object)
VALUES
    ('Auth Pattern',         'leads_to',  'Login Bug'),
    ('Auth Pattern',         'relates_to', 'External Auth Service'),
    ('External Auth Service', 'uses',      'Login Bug'),
    ('Unknown Tool',         'uses',      'UI Decision');
