/**
 * browse-ui/src/lib/hosts/pairing.ts
 *
 * Client-side utilities for the QR / browse:// pairing flow (issue #58).
 *
 * The pairing URL scheme is:
 *   browse://connect?ticket=<base64url_json>
 *
 * The JSON payload contains:
 *   url          — backend base URL
 *   nonce        — 32-hex-char random nonce
 *   created_at   — Unix timestamp (seconds)
 *   max_age_seconds — signed ticket TTL (defaults to 300; static slots use 86400)
 *   token_hmac   — HMAC-SHA256(token, nonce_bytes || created_at_le64)
 *                  Empty string for open-auth backends.
 *
 * The UI side of pairing:
 * 1. Accepts a `browse://connect?ticket=...` URL pasted or typed by the user.
 * 2. Decodes the ticket payload and extracts the backend base URL.
 * 3. Pre-fills the "Add host" form with the discovered URL.
 *    The token itself is NOT included in the ticket (it would leak it).
 *    Instead, the HMAC proof confirms that the ticket was generated by the
 *    operator who holds the real token — the user still enters the token
 *    only once when adding the host.
 *
 * Note: Full HMAC verification requires the operator token, which the client
 * does not hold at pairing-scan time. The backend performs authoritative
 * verification on first authenticated request. The client verifies:
 *   - ticket is well-formed JSON
 *   - created_at is within the freshness window
 *   - url is a reachable http(s) address
 */

import { z } from "zod";

// ── Ticket payload schema ──────────────────────────────────────────────────────

export const pairingTicketPayloadSchema = z.object({
  url: z
    .string()
    .url()
    .refine((value) => value.startsWith("http://") || value.startsWith("https://"), {
      message: "base URL must use http or https",
    }),
  nonce: z.string().min(16),
  created_at: z.number().int().positive(),
  max_age_seconds: z.number().int().positive().optional(),
  /** HMAC-SHA256 proof — empty string for open-auth backends. */
  token_hmac: z.string(),
});

export type PairingTicketPayload = z.infer<typeof pairingTicketPayloadSchema>;

/** Default maximum ticket age the UI accepts (5 minutes). */
const DEFAULT_MAX_TICKET_AGE_MS = 5 * 60 * 1000;

// ── Base64url decode ───────────────────────────────────────────────────────────

function b64urlDecode(s: string): Uint8Array {
  // Restore padding
  const pad = (4 - (s.length % 4)) % 4;
  const padded = s + "=".repeat(pad);
  // Replace URL-safe chars
  const standard = padded.replace(/-/g, "+").replace(/_/g, "/");
  const binary = atob(standard);
  return Uint8Array.from(binary, (c) => c.charCodeAt(0));
}

// ── Parse result ──────────────────────────────────────────────────────────────

export type ParsePairingUrlResult =
  | { ok: true; payload: PairingTicketPayload; baseUrl: string; isOpenAuth: boolean }
  | { ok: false; error: string };

/**
 * Parse and validate a `browse://connect?ticket=...` URL (or a raw ticket string).
 *
 * Returns the decoded payload on success, or an error message on failure.
 * Does NOT verify the HMAC proof (that requires the operator token, which the
 * UI does not hold at scan time).
 */
export function parsePairingUrl(input: string): ParsePairingUrlResult {
  const raw = input.trim();

  let ticketStr: string;

  if (raw.startsWith("browse://")) {
    // Extract ticket= query param from a browse:// URL
    const questionIdx = raw.indexOf("?");
    if (questionIdx === -1) {
      return { ok: false, error: "Invalid browse:// URL — missing query string." };
    }
    const query = raw.slice(questionIdx + 1);
    const params = new URLSearchParams(query);
    const ticket = params.get("ticket");
    if (!ticket) {
      return { ok: false, error: "Invalid browse:// URL — missing 'ticket' parameter." };
    }
    ticketStr = ticket;
  } else {
    // Accept a raw base64url ticket directly
    ticketStr = raw;
  }

  // Decode base64url
  let decoded: Uint8Array;
  try {
    decoded = b64urlDecode(ticketStr);
  } catch {
    return { ok: false, error: "Ticket is not valid base64url." };
  }

  // Parse JSON payload
  let jsonObj: unknown;
  try {
    jsonObj = JSON.parse(new TextDecoder().decode(decoded));
  } catch {
    return { ok: false, error: "Ticket payload is not valid JSON." };
  }

  // Schema validation
  const parsed = pairingTicketPayloadSchema.safeParse(jsonObj);
  if (!parsed.success) {
    const firstError = parsed.error.issues[0]?.message ?? "unknown schema error";
    return { ok: false, error: `Ticket schema invalid: ${firstError}` };
  }

  const payload = parsed.data;

  // Freshness check (client-side best-effort — backend performs authoritative check)
  const maxAgeMs = (payload.max_age_seconds ?? DEFAULT_MAX_TICKET_AGE_MS / 1000) * 1000;
  const ageMs = Date.now() - payload.created_at * 1000;
  if (ageMs < 0 || ageMs > maxAgeMs) {
    const ageSec = Math.round(ageMs / 1000);
    return {
      ok: false,
      error: `Ticket has expired (age ${ageSec}s, max ${maxAgeMs / 1000}s). Ask the operator to re-run --print-pairing-qr.`,
    };
  }

  return {
    ok: true,
    payload,
    baseUrl: payload.url,
    isOpenAuth: payload.token_hmac === "",
  };
}

/**
 * Return true when a string looks like a browse:// pairing URL.
 * Fast path used to show the QR panel automatically when the user types/pastes.
 */
export function looksLikePairingUrl(input: string): boolean {
  const raw = input.trim();
  if (raw.startsWith("browse://connect?ticket=")) return true;
  // Allow raw base64url tickets (no spaces, long enough to plausibly be a ticket)
  if (!raw.startsWith("browse://") && !raw.startsWith("http") && raw.length >= 40) {
    return /^[A-Za-z0-9\-_]+$/.test(raw);
  }
  return false;
}

// ── Server-side authoritative ticket verification (#58) ───────────────────────

export type ServerVerifyResult =
  | { ok: true; baseUrl: string; serverVerified: true }
  | { ok: false; error: string; serverReachable: boolean };

/**
 * Call `POST {backendBaseUrl}/.well-known/browse-host/verify` to perform
 * authoritative server-side HMAC verification of a pairing ticket.
 *
 * This endpoint is open (no Bearer token required), making it safe to call
 * during the pairing flow before the user has provided a token.
 *
 * On network failure, returns `{ ok: false, serverReachable: false }` so the
 * caller can decide whether to fall back to client-only validation.
 */
export async function verifyPairingTicketServer(
  backendBaseUrl: string,
  ticket: string,
  maxAgeSeconds = 300
): Promise<ServerVerifyResult> {
  const url = `${backendBaseUrl.replace(/\/$/, "")}/.well-known/browse-host/verify`;
  let resp: Response;
  try {
    resp = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ticket, max_age_seconds: maxAgeSeconds }),
      // Short timeout — if the server is unreachable, fail fast.
      signal: AbortSignal.timeout(5000),
    });
  } catch (err) {
    return {
      ok: false,
      error: err instanceof Error ? err.message : String(err),
      serverReachable: false,
    };
  }

  let data: { valid?: boolean; base_url?: string; error?: string };
  try {
    data = (await resp.json()) as { valid?: boolean; base_url?: string; error?: string };
  } catch {
    return {
      ok: false,
      error: resp.ok
        ? "Server returned an invalid verification response."
        : `Server returned HTTP ${resp.status} during verification.`,
      serverReachable: true,
    };
  }

  if (data.valid) {
    return { ok: true, baseUrl: data.base_url ?? backendBaseUrl, serverVerified: true };
  }
  return {
    ok: false,
    error:
      data.error ??
      (resp.ok
        ? "Server rejected the ticket."
        : `Server returned HTTP ${resp.status} during verification.`),
    serverReachable: true,
  };
}
